version: "2.0"

services:
  arena:
    image: ghcr.io/yieldswarm/yieldswarm-arena:latest
    expose:
      - port: 3000
        as: 80
        to:
          - global: true
    env:
      - NEXT_PUBLIC_API_BASE_URL=https://api.yieldswarm-v2.vercel.app

profiles:
  compute:
    arena:
      resources:
        cpu:
          units: 1.5
        memory:
          size: 2Gi
        storage:
          size: 10Gi

  placement:
    akash:
      attributes:
        host: akash
      pricing:
        arena:
          denom: uakt
          amount: 750

deployment:
  arena:
    akash:
      count: 1