FROM nvidia/cuda:12.4.1-runtime-ubuntu22.04

RUN apt-get update && apt-get install -y curl ca-certificates
RUN curl -fsSL https://ollama.com/install.sh | sh

WORKDIR /app
COPY entrypoint.sh .
RUN chmod +x entrypoint.sh

EXPOSE 11434

ENTRYPOINT ["./entrypoint.sh"]